import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
    blog: [
        {
            type: 'autogenerated',
            dirName: 'blog',
        },
    ],
    linux: [
        {},
    ],
    driver: [
        {},
    ],
};

export default sidebars;
